fix: Use name of other participant on archived rooms
famedly/matrix-dart-sdk pull request #1708
Opened 2024-02-16 10:49 UTC by Pat992

Previously archived rooms where called Empty chat (was <Your own username>).
Now the other username is selected in case of direct chats that are archived, via the room-member-states and client-userID

2024-02-16 18:31 UTC, td-famedly commented on lib/src/room.dart
> +      if (otherRoomMember?.value.prevContent?.tryGet('displayname') != null) {
why prevContent here?

2024-02-16 18:31 UTC, td-famedly commented on lib/src/room.dart
> +    if (isArchived) {
Could just go in the membership.leave block

2024-02-16 18:31 UTC, td-famedly commented on lib/src/room.dart
> +      final roomMemberEvents = states.entries
hm idm this, but you could also just use directChatMatrixId to simplify this

2024-02-28 18:15 UTC, td-famedly requested changes

2024-02-28 18:15 UTC, td-famedly commented on lib/src/room.dart
> +      if (directChatMatrixID != null) {
I would merge this with the lines just below this, looks like prev_sender is never sent in member events

2024-03-01 11:01 UTC, krille-chan approved these changes
LGTM 👍

2024-03-01 11:13 UTC, merged